jQuery(function($){'use strict';var cloneIndex={set:function($inputs,index){$inputs.each(function(){var $field=$(this);var name=this.name;if(name&&!$field.closest('.rwmb-group-clone').length){$field.attr('name',cloneIndex.replace(index,name,'[',']',false));}
var id=this.id;if(id){$field.attr('id',cloneIndex.replace(index,id,'_','',true,true));}
$field.trigger('update_index',index);});var $address=$inputs.filter('.rwmb-map-goto-address-button');if($address.length){var value=$address.attr('value');$address.attr('value',cloneIndex.replace(index,value,'_'));}},replace:function(index,value,before,after,alternative,isEnd){before=before||'';after=after||'';if(typeof alternative==='undefined'){alternative=true;}
var end=isEnd?'$':'';var regex=new RegExp(cloneIndex.escapeRegex(before)+'(\\d+)'+cloneIndex.escapeRegex(after)+end),newValue=before+index+after;return regex.test(value)?value.replace(regex,newValue):(alternative?value+newValue:value);},escapeRegex:function(string){return string.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");},nextIndex:function($container){var nextIndex=$container.data('next-index');$container.data('next-index',nextIndex+1);return nextIndex;}};var cloneValue={reset:function(){cloneValue.$field=$(this);cloneValue.type=cloneValue.$field.attr('type');cloneValue.isHiddenField=cloneValue.$field.hasClass('rwmb-hidden');if(true===cloneValue.$field.data('clone-default')){cloneValue.resetToDefault();}else{cloneValue.clear();}},resetToDefault:function(){var defaultValue=cloneValue.$field.data('default');if('radio'===cloneValue.type){cloneValue.$field.prop('checked',cloneValue.$field.val()===defaultValue);}else if('checkbox'===cloneValue.type){cloneValue.$field.prop('checked',!!defaultValue);}else if('select'===cloneValue.type){cloneValue.$field.find('option[value="'+defaultValue+'"]').prop('selected',true);}else if(!cloneValue.isHiddenField){cloneValue.$field.val(defaultValue);}},clear:function(){if('radio'===cloneValue.type||'checkbox'===cloneValue.type){cloneValue.$field.prop('checked',false);}else if('select'===cloneValue.type){cloneValue.$field.prop('selectedIndex',-1);}else if(!cloneValue.isHiddenField){cloneValue.$field.val('');}}};function clone($container){var $last=$container.children('.rwmb-clone').last(),$clone=$last.clone(),inputSelectors='input[class*="rwmb"], textarea[class*="rwmb"], select[class*="rwmb"], button[class*="rwmb"]',nextIndex=cloneIndex.nextIndex($container);var $inputs=$clone.find(inputSelectors);$inputs.each(cloneValue.reset);$clone.insertAfter($last);$clone.trigger('clone_instance',nextIndex);cloneIndex.set($inputs,nextIndex);$inputs.trigger('clone',nextIndex);$inputs.trigger('after_clone',nextIndex);}
function toggleRemoveButtons($container){var $clones=$container.children('.rwmb-clone');$clones.children('.remove-clone').toggle($clones.length>1);$container.find('.rwmb-input').each(function(){toggleRemoveButtons($(this));});}
function toggleAddButton($container){var $button=$container.children('.add-clone'),maxClone=parseInt($container.data('max-clone')),numClone=$container.children('.rwmb-clone').length;$button.toggle(isNaN(maxClone)||(maxClone&&numClone<maxClone));}
function initSortable(){$('.rwmb-input').each(function(){var $container=$(this);if(undefined!==$container.sortable('instance')){return;}
$container.sortable({handle:'.rwmb-clone-icon',placeholder:' rwmb-clone rwmb-sortable-placeholder',items:'> .rwmb-clone',start:function(event,ui){ui.placeholder.height(ui.item.outerHeight());}});});}
$(document).on('click','.add-clone',function(e){e.preventDefault();var $container=$(this).closest('.rwmb-input');clone($container);toggleRemoveButtons($container);toggleAddButton($container);initSortable();}).on('click','.remove-clone',function(e){e.preventDefault();var $this=$(this),$container=$this.closest('.rwmb-input');if($container.children('.rwmb-clone').length<2){return;}
$this.parent().trigger('remove').remove();toggleRemoveButtons($container);toggleAddButton($container);});$('.rwmb-input').each(function(){var $container=$(this);toggleRemoveButtons($container);toggleAddButton($container);$container.data('next-index',$container.children('.rwmb-clone').length).sortable({handle:'.rwmb-clone-icon',placeholder:' rwmb-clone rwmb-sortable-placeholder',items:'> .rwmb-clone',start:function(event,ui){ui.placeholder.height(ui.item.outerHeight());$(ui.item).find('.rwmb-wysiwyg').each(function(){tinymce.execCommand('mceRemoveEditor',false,this.id);});},stop:function(e,ui){$(ui.item).find('.rwmb-wysiwyg').each(function(){tinymce.execCommand('mceAddEditor',true,this.id);});}});});});